# Generated by Django 3.1.6 on 2021-02-17 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagentes_reacao', models.CharField(max_length=30)),
                ('produtos_reacao', models.CharField(max_length=30)),
                ('data_da_pesquisa', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data da pesquisa')),
            ],
        ),
    ]
