# Generated by Django 3.1.6 on 2021-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estequiometria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPeriodica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField()),
                ('symbol', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=20)),
                ('atomic_mass', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
